### ISSUE TITLE
Display a different message when there is nothing to report

### ISSUE THREAD

**Issue by agarzola** [ChromaticHQ/bamboo-outofoffice-slack#6]
## Description
When BambooHR returns no upcoming holidays and no team members out of office, the messaging should be something different, like:
> Hey, team! There are no upcoming holidays and no one is scheduled to be out of office in the next two weeks. For more info, contact `@hr`.

## Current behavior
The same messaging appears as when there _are_ upcoming holidays or team members out of office.

## Screenshots
![screenshot](https://p191.p3.n0.cdn.getcloudapp.com/items/qGudAv7w/Image%202020-04-13%20at%206.47.57%20AM.png?v=e2727a26edbea0773ca5ec11ab45e30e)

**Comment by apotek** [comment]
We have killed this feature so we will not be fixing this.
