### ISSUE TITLE
Improve message for a single day off

### ISSUE THREAD

**Issue by agarzola** [ChromaticHQ/bamboo-outofoffice-slack#7]
## Description
When a team member has a single day off scheduled for PTO, this integration returns something like:
>**Testy McTestface**
>Out of office from Friday, June 19, 2020 to Friday, June 19, 2020.

This is a bit awkward to read and has, in more than one occasion, made me want to read it twice just to make sure I got it right. This message could be improved to avoid the from/to language in the case of a single day of PTO.

## Proposed Solution
Compare the start and end dates for a team member’s PTO and modify the message if they are the same date. Something like this:
>**Testy McTestface**
>Out of office on Friday, June 19, 2020.

## Alternatives Considered
N/A

## Additional Context
N/A

**Comment by apotek** [comment]
This looks like it was completed. Closing.
